// Generated by gencpp from file self_msgs_and_srvs/GlbObsRcv.msg
// DO NOT EDIT!


#ifndef SELF_MSGS_AND_SRVS_MESSAGE_GLBOBSRCV_H
#define SELF_MSGS_AND_SRVS_MESSAGE_GLBOBSRCV_H

#include <ros/service_traits.h>


#include <self_msgs_and_srvs/GlbObsRcvRequest.h>
#include <self_msgs_and_srvs/GlbObsRcvResponse.h>


namespace self_msgs_and_srvs
{

struct GlbObsRcv
{

typedef GlbObsRcvRequest Request;
typedef GlbObsRcvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GlbObsRcv
} // namespace self_msgs_and_srvs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::self_msgs_and_srvs::GlbObsRcv > {
  static const char* value()
  {
    return "7f352b44c251978f0843cd60887550cf";
  }

  static const char* value(const ::self_msgs_and_srvs::GlbObsRcv&) { return value(); }
};

template<>
struct DataType< ::self_msgs_and_srvs::GlbObsRcv > {
  static const char* value()
  {
    return "self_msgs_and_srvs/GlbObsRcv";
  }

  static const char* value(const ::self_msgs_and_srvs::GlbObsRcv&) { return value(); }
};


// service_traits::MD5Sum< ::self_msgs_and_srvs::GlbObsRcvRequest> should match
// service_traits::MD5Sum< ::self_msgs_and_srvs::GlbObsRcv >
template<>
struct MD5Sum< ::self_msgs_and_srvs::GlbObsRcvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::self_msgs_and_srvs::GlbObsRcv >::value();
  }
  static const char* value(const ::self_msgs_and_srvs::GlbObsRcvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::self_msgs_and_srvs::GlbObsRcvRequest> should match
// service_traits::DataType< ::self_msgs_and_srvs::GlbObsRcv >
template<>
struct DataType< ::self_msgs_and_srvs::GlbObsRcvRequest>
{
  static const char* value()
  {
    return DataType< ::self_msgs_and_srvs::GlbObsRcv >::value();
  }
  static const char* value(const ::self_msgs_and_srvs::GlbObsRcvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::self_msgs_and_srvs::GlbObsRcvResponse> should match
// service_traits::MD5Sum< ::self_msgs_and_srvs::GlbObsRcv >
template<>
struct MD5Sum< ::self_msgs_and_srvs::GlbObsRcvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::self_msgs_and_srvs::GlbObsRcv >::value();
  }
  static const char* value(const ::self_msgs_and_srvs::GlbObsRcvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::self_msgs_and_srvs::GlbObsRcvResponse> should match
// service_traits::DataType< ::self_msgs_and_srvs::GlbObsRcv >
template<>
struct DataType< ::self_msgs_and_srvs::GlbObsRcvResponse>
{
  static const char* value()
  {
    return DataType< ::self_msgs_and_srvs::GlbObsRcv >::value();
  }
  static const char* value(const ::self_msgs_and_srvs::GlbObsRcvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // SELF_MSGS_AND_SRVS_MESSAGE_GLBOBSRCV_H
