(cl:defpackage self_msgs_and_srvs-srv
  (:use )
  (:export
   "GLBOBSRCV"
   "<GLBOBSRCV-REQUEST>"
   "GLBOBSRCV-REQUEST"
   "<GLBOBSRCV-RESPONSE>"
   "GLBOBSRCV-RESPONSE"
   "LEARNINGSAMPLER"
   "<LEARNINGSAMPLER-REQUEST>"
   "LEARNINGSAMPLER-REQUEST"
   "<LEARNINGSAMPLER-RESPONSE>"
   "LEARNINGSAMPLER-RESPONSE"
  ))

