# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from self_msgs_and_srvs/input_point.msg. Do not edit."""
import codecs
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct

import geometry_msgs.msg

class input_point(genpy.Message):
  _md5sum = "4b446b61e7be949357360ca65dc198b5"
  _type = "self_msgs_and_srvs/input_point"
  _has_header = False  # flag to mark the presence of a Header object
  _full_text = """geometry_msgs/Point cur_pos
geometry_msgs/Point pred_pos
geometry_msgs/Point succ_pos

geometry_msgs/Point target_pos
geometry_msgs/Point target_vel
geometry_msgs/Point target_acc

================================================================================
MSG: geometry_msgs/Point
# This contains the position of a point in free space
float64 x
float64 y
float64 z
"""
  __slots__ = ['cur_pos','pred_pos','succ_pos','target_pos','target_vel','target_acc']
  _slot_types = ['geometry_msgs/Point','geometry_msgs/Point','geometry_msgs/Point','geometry_msgs/Point','geometry_msgs/Point','geometry_msgs/Point']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       cur_pos,pred_pos,succ_pos,target_pos,target_vel,target_acc

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(input_point, self).__init__(*args, **kwds)
      # message fields cannot be None, assign default values for those that are
      if self.cur_pos is None:
        self.cur_pos = geometry_msgs.msg.Point()
      if self.pred_pos is None:
        self.pred_pos = geometry_msgs.msg.Point()
      if self.succ_pos is None:
        self.succ_pos = geometry_msgs.msg.Point()
      if self.target_pos is None:
        self.target_pos = geometry_msgs.msg.Point()
      if self.target_vel is None:
        self.target_vel = geometry_msgs.msg.Point()
      if self.target_acc is None:
        self.target_acc = geometry_msgs.msg.Point()
    else:
      self.cur_pos = geometry_msgs.msg.Point()
      self.pred_pos = geometry_msgs.msg.Point()
      self.succ_pos = geometry_msgs.msg.Point()
      self.target_pos = geometry_msgs.msg.Point()
      self.target_vel = geometry_msgs.msg.Point()
      self.target_acc = geometry_msgs.msg.Point()

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      _x = self
      buff.write(_get_struct_18d().pack(_x.cur_pos.x, _x.cur_pos.y, _x.cur_pos.z, _x.pred_pos.x, _x.pred_pos.y, _x.pred_pos.z, _x.succ_pos.x, _x.succ_pos.y, _x.succ_pos.z, _x.target_pos.x, _x.target_pos.y, _x.target_pos.z, _x.target_vel.x, _x.target_vel.y, _x.target_vel.z, _x.target_acc.x, _x.target_acc.y, _x.target_acc.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.cur_pos is None:
        self.cur_pos = geometry_msgs.msg.Point()
      if self.pred_pos is None:
        self.pred_pos = geometry_msgs.msg.Point()
      if self.succ_pos is None:
        self.succ_pos = geometry_msgs.msg.Point()
      if self.target_pos is None:
        self.target_pos = geometry_msgs.msg.Point()
      if self.target_vel is None:
        self.target_vel = geometry_msgs.msg.Point()
      if self.target_acc is None:
        self.target_acc = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 144
      (_x.cur_pos.x, _x.cur_pos.y, _x.cur_pos.z, _x.pred_pos.x, _x.pred_pos.y, _x.pred_pos.z, _x.succ_pos.x, _x.succ_pos.y, _x.succ_pos.z, _x.target_pos.x, _x.target_pos.y, _x.target_pos.z, _x.target_vel.x, _x.target_vel.y, _x.target_vel.z, _x.target_acc.x, _x.target_acc.y, _x.target_acc.z,) = _get_struct_18d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      _x = self
      buff.write(_get_struct_18d().pack(_x.cur_pos.x, _x.cur_pos.y, _x.cur_pos.z, _x.pred_pos.x, _x.pred_pos.y, _x.pred_pos.z, _x.succ_pos.x, _x.succ_pos.y, _x.succ_pos.z, _x.target_pos.x, _x.target_pos.y, _x.target_pos.z, _x.target_vel.x, _x.target_vel.y, _x.target_vel.z, _x.target_acc.x, _x.target_acc.y, _x.target_acc.z))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    if python3:
      codecs.lookup_error("rosmsg").msg_type = self._type
    try:
      if self.cur_pos is None:
        self.cur_pos = geometry_msgs.msg.Point()
      if self.pred_pos is None:
        self.pred_pos = geometry_msgs.msg.Point()
      if self.succ_pos is None:
        self.succ_pos = geometry_msgs.msg.Point()
      if self.target_pos is None:
        self.target_pos = geometry_msgs.msg.Point()
      if self.target_vel is None:
        self.target_vel = geometry_msgs.msg.Point()
      if self.target_acc is None:
        self.target_acc = geometry_msgs.msg.Point()
      end = 0
      _x = self
      start = end
      end += 144
      (_x.cur_pos.x, _x.cur_pos.y, _x.cur_pos.z, _x.pred_pos.x, _x.pred_pos.y, _x.pred_pos.z, _x.succ_pos.x, _x.succ_pos.y, _x.succ_pos.z, _x.target_pos.x, _x.target_pos.y, _x.target_pos.z, _x.target_vel.x, _x.target_vel.y, _x.target_vel.z, _x.target_acc.x, _x.target_acc.y, _x.target_acc.z,) = _get_struct_18d().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e)  # most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_18d = None
def _get_struct_18d():
    global _struct_18d
    if _struct_18d is None:
        _struct_18d = struct.Struct("<18d")
    return _struct_18d
